version: 2.1
orbs:
    codecov: codecov/codecov@1.0.2
job: &job
    working_directory: ~/repo
    steps:
        - checkout
        - run: yarn cache clean
        - run: yarn install
        - run: yarn test
job_coverage: &job_coverage
    working_directory: ~/repo
    steps:
        - checkout
        - run: yarn cache clean
        - run: yarn install
        - run: yarn test:cov
    coverage:
        - codecov/upload:
              file: ~/repo/coverage/lcov.info
        - codecov/upload:
              file: ~/repo/coverage/clover.xml
workflows:
    test:
        jobs:
            - test-latest
            - test-dubnium
            - test-carbon
            - publish-github-release
jobs:
    test-latest:
        docker:
            - image: circleci/node:latest
        <<: *job_coverage
    test-carbon:
        docker:
            - image: circleci/node:carbon
        <<: *job
    test-dubnium:
        docker:
            - image: circleci/node:dubnium
        <<: *job
