version: 2.1
orbs:
    codecov: codecov/codecov@1.0.2
workflows:
    test:
        jobs:
            - test-latest
            - test-carbon
            - test-dubnium
jobs:
    test-latest: &test-template
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout
            - run: yarn cache clean
            - run: yarn install
            - run: yarn test
            - codecov/upload:
                  file: coverage/lcov.info
            - codecov/upload:
                  file: coverage/clover.xml
    test-carbon:
        <<: *test-template
        docker:
            - image: circleci/node:carbon
    test-dubnium:
        <<: *test-template
        docker:
            - image: circleci/node:dubnium
